security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UsersAuthenticator
            logout:
                path: app_logout

    access_control:
        # Allow access to the login page and registration page (if any)
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

        # Restrict access to all other pages
        - { path: ^/dashbord, roles: ROLE_USER }
        - { path: ^/creerPortefeuille, roles: ROLE_USER }
        - { path: ^/affichercompte, roles: ROLE_USER }
        - { path: ^/infoIdentite, roles: ROLE_USER }
        - { path: ^/consulter_historique, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
